# tcz-proxy configuration file

# Default host to proxy requests to
# This is used when no path mapping matches
default_host: https://repo.example.com

# Path mappings for redirecting specific patterns to different destinations
# Each mapping consists of:
# - from: A regex pattern to match against the request path
# - to: The destination URL with capture group references ($1, $2, etc.)
path_mappings:
  # Example: Redirect watchdog.tcz to GitHub releases
  # Matches: /repo/14.x/aarch64/tcz/watchdog.tcz
  # Results in: https://github.com/asssaf/picore-watchdog/releases/download/14/watchdog-aarch64.zip
  - from: .*/(\d+)\.x/(aarch64|armhf)/tcz/watchdog\.tcz
    to: https://github.com/asssaf/picore-watchdog/releases/download/$1/watchdog-$2.zip

  # Example: Redirect API calls to a different server
  - from: /api/v(\d+)/(.+)
    to: https://api.example.com/v$1/$2

  # Example: Redirect specific packages to a mirror
  - from: /packages/(\d+\.x)/(.+)/(.+\.tcz)
    to: https://mirror.example.org/tinycorelinux/$1/$2/$3
