# tcz-proxy configuration file

# Default host to proxy requests to
# This is used when no path mapping matches
default_host: http://tinycorelinux.net

# Whether to automatically follow redirects
# When true, the proxy follows redirects and returns the final response to the client
# When false (default), the proxy returns redirect responses as-is
follow_redirects: true

# Path mappings for redirecting specific patterns to different destinations
# Each mapping consists of:
# - from: A regex pattern to match against the request path
# - to: The destination URL with capture group references ($1, $2, etc.)
path_mappings:
  # Example: Redirect watchdog.tcz to GitHub releases
  # Matches: /repo/14.x/aarch64/tcz/watchdog.tcz
  # Results in: https://github.com/asssaf/picore-watchdog/releases/download/14/watchdog-aarch64.zip
  - from: .*/(\d+)\.x/(aarch64|armhf)/tcz/(tryboot)\.tcz(.*)
    to: https://raw.githubusercontent.com/asssaf/picore-$3/refs/heads/tcz-v0.0.1/$1.x/$2/tcz/$3.tcz$4
  - from: .*/(\d+)\.x/(aarch64|armhf)/tcz/(busybox-system)\.tcz(.*)
    to: https://raw.githubusercontent.com/asssaf/picore-$3/refs/heads/tcz-v0.0.1/$1.x/$2/tcz/$3.tcz$4
  - from: .*/(\d+)\.x/(aarch64|armhf)/tcz/(watchdog)\.tcz(.*)
    to: https://raw.githubusercontent.com/asssaf/picore-$3/refs/heads/tcz-v0.0.1/$1.x/$2/tcz/$3.tcz$4
